### ISSUE TITLE
Possible overload?

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#204] opened 2020-06-15 12:48 UTC
Hi, 

I am not sure about this, but is it possible that, as several students are using LEMONADE, the platform is experiencing some overload issues?

A student asked for help on his workflow yesterday, showing that even if **Read data** had a suitable result, it seemed that **Box plot** didn't, merging the columns all together.

--Result for **Read data**:
![image](https://user-images.githubusercontent.com/24958541/84658847-e2466300-aeec-11ea-8aa8-05d250e1bab8.png)

--Error for **Box plot** when the user has to select the attributes:
![image](https://user-images.githubusercontent.com/24958541/84658919-fe4a0480-aeec-11ea-8817-00015256cf0a.png)

--Expected for **Box plot**:
![image](https://user-images.githubusercontent.com/24958541/84659005-220d4a80-aeed-11ea-9ff8-1b9b7fc5184c.png)

**However, when he tried again later, it properly worked.** So, that is why I am claiming it would be an overload issue...

**Workflow id:** 1725

Thanks in advance.

Alex de Sá

**Comment by waltersf** [comment] 2020-06-16 13:36
No, it is not an overload issue. The process of suggesting attributes is executed in the client side (Javascript). The problem is related to the way the JS framework (Vue) and the library that computes suggestions (Tahiti.js) interact with each other. I fixed a bug, probably you refreshed the page and then the latest version fixed the problem or it was fixed by saving the workflow.

**Closed** 2020-06-16 14:11 UTC
