### ISSUE TITLE
Autosaving

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#11] opened 2019-02-01 01:08 UTC
As a suggestion, I recommend to automatically save the workflow for the user (e.g., every five minutes the system automatically saves the workflow).

Or even a message warning possible data lost if the user decides to change from the current environment to another: 
"Do you want save the workflow before leaving? [Yes/No]"

**Comment by waltersf** [comment] 2019-05-20 21:09
Second suggestion implies this issue is duplicate of #76

**Comment by waltersf** [comment] 2019-05-20 21:09
Duplicate of #76

**Closed by waltersf** 2019-05-20 21:09 UTC
Labels: enhancement

**Comment by alexgcsa** [comment] 2019-05-20 22:39
Alright.

Thanks,

Alex
