### ISSUE TITLE
"Saving as image" is adding other things in the generated image

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#51] opened 2019-02-09 18:12 UTC
When trying to use the option "Save as image", I observed that this option is adding some lines in the output image:

![image](https://user-images.githubusercontent.com/24958541/52524555-503da300-2c85-11e9-9bd8-526f13e7d2b2.png)

The workflow id 71 does not have this line upon "Converter categórico para numérico".

**Comment by alexgcsa** [comment] 2019-02-09 18:15
You can see it in the original image:

![image](https://user-images.githubusercontent.com/24958541/52524607-ed98d700-2c85-11e9-81f1-eb36d00def8b.png)

**Comment by waltersf** [comment] 2019-02-22 21:53
@alexgcsa I couldn't reproduce it. Please, test using other flows. I'll close this issue, if the problem perists, please reopen it.

**Closed by waltersf** 2019-02-22 21:53 UTC
